apiVersion: gateway.networking.k8s.io/v1beta1
#This is a limitation of kind - 1.28 is still and additional image
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
